USE [master]
GO
/****** Object:  Database [FlowerInventoryAssessment]    Script Date: 06/04/2025 11:20:08 pm ******/
CREATE DATABASE [FlowerInventoryAssessment]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FlowerInventoryAssessment', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\FlowerInventoryAssessment.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FlowerInventoryAssessment_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\FlowerInventoryAssessment_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [FlowerInventoryAssessment] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FlowerInventoryAssessment].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FlowerInventoryAssessment] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET ARITHABORT OFF 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET  MULTI_USER 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FlowerInventoryAssessment] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FlowerInventoryAssessment] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [FlowerInventoryAssessment] SET QUERY_STORE = ON
GO
ALTER DATABASE [FlowerInventoryAssessment] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [FlowerInventoryAssessment]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 06/04/2025 11:20:08 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[ID] [int] NOT NULL,
	[Timestamp] [datetime2](0) NOT NULL,
	[Name] [nvarchar](150) NOT NULL,
	[Description] [nvarchar](750) NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Flowers]    Script Date: 06/04/2025 11:20:08 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Flowers](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Timestamp] [datetime2](0) NOT NULL,
	[Name] [nvarchar](150) NOT NULL,
	[Description] [nvarchar](750) NULL,
	[Price] [decimal](9, 2) NOT NULL,
	[TotalInventory] [int] NOT NULL,
	[CategoryID] [int] NOT NULL,
	[ImageUri] [nvarchar](max) NULL,
	[IsActive] [bit] NOT NULL,
	[DeletionTimestamp] [datetimeoffset](7) NULL,
	[LastUpdateTimestamp] [datetimeoffset](7) NULL,
 CONSTRAINT [PK_Flowers] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Flowers]  WITH CHECK ADD  CONSTRAINT [FK_Flowers_Categories] FOREIGN KEY([CategoryID])
REFERENCES [dbo].[Categories] ([ID])
GO
ALTER TABLE [dbo].[Flowers] CHECK CONSTRAINT [FK_Flowers_Categories]
GO
USE [master]
GO
ALTER DATABASE [FlowerInventoryAssessment] SET  READ_WRITE 
GO
